name: fiyaka
description: fiyaka mobile application

# don't publish to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # 3rd party
  get_it: ^5.0.1
  dio: ^3.0.10
  json_annotation: ^3.1.1
  device_info: ^1.0.0
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+17
  animations: ^1.1.2
  bubble: ^1.1.9+1

  # stacked architecture
  observable_ish: ^2.1.4
  stacked: ^1.7.6
  stacked_services: ^0.5.4+4
  stacked_hooks: ^0.1.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.0.0
  json_serializable: ^3.5.0
  flash: ^1.3.1

flutter_icons:
  image_path: "asset/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - asset/app_icon.png
    - asset/images/avatar.png

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: asset/font/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: asset/font/SF-Pro-Display-Semibold.ttf
          weight: 600
        - asset: asset/font/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: asset/font/SF-Pro-Display-Regular.ttf